// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DemonstrationProject.DomainObjects.DmCustomerBillJsonTypes;

namespace DemonstrationProject.DomainObjects.DmCustomerBillJsonTypes
{

    public class BuyAndKeep
    {

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("cost")]
        public double Cost { get; set; }
    }

}
