// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DemonstrationProject.DomainObjects.DmCustomerBillJsonTypes;

namespace DemonstrationProject.DomainObjects.DmCustomerBillJsonTypes
{

    public class Call
    {

        [JsonProperty("called")]
        public string Called { get; set; }

        [JsonProperty("duration")]
        public string Duration { get; set; }

        [JsonProperty("cost")]
        public double Cost { get; set; }
    }

}
