// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DemonstrationProject.DomainObjects.DmCustomerBillJsonTypes;

namespace DemonstrationProject.DomainObjects.DmCustomerBillJsonTypes
{

    internal class Package
    {

        [JsonProperty("subscriptions")]
        public Subscription[] Subscriptions { get; set; }

        [JsonProperty("total")]
        public double Total { get; set; }
    }

}
