// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DemonstrationProject.DomainObjects.DmCustomerBillJsonTypes;

namespace DemonstrationProject.DomainObjects.DmCustomerBillJsonTypes
{

    public class Statement
    {

        [JsonProperty("generated")]
        public string Generated { get; set; }

        [JsonProperty("due")]
        public string Due { get; set; }

        [JsonProperty("period")]
        public Period Period { get; set; }
    }

}
